// packages/react/src/components/Spinner/Spinner.tsx
import type * as React from 'react';
import cl from 'clsx';

import { useSynchronizedAnimation } from '../../hooks';

import classes from './Spinner.module.css';

const sizeMap: { [key in NonNullable<SpinnerProps['size']>]: number } = {
  xxsmall: 13,
  xsmall: 20,
  small: 27,
  medium: 40,
  large: 56,
  xlarge: 79,
};

export type SpinnerProps = {
  /** Spinner title  */
  title: string;
  /** Spinner size  */
  size?: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge';
  /** Spinner appearance  */
  variant?: 'default' | 'interaction' | 'inverted';
} & React.ComponentPropsWithoutRef<'svg'>;

/**  Spinner component used for indicating busy or indeterminate loading */
export const Spinner = ({
  title,
  size = 'medium',
  variant = 'default',
  className,
  style,
  ...rest
}: SpinnerProps): JSX.Element => {
  const svgRef = useSynchronizedAnimation<SVGSVGElement>(
    classes['rotate-animation'],
  );

  const strokeRef = useSynchronizedAnimation<SVGCircleElement>(
    classes['stroke-animation'],
  );

  return (
    <svg
      className={cl(classes.spinner, className)}
      style={{ width: sizeMap[size], height: sizeMap[size], ...style }}
      viewBox='0 0 50 50'
      ref={svgRef}
      {...rest}
    >
      <title>{title}</title>
      <circle
        className={cl(
          classes.background,
          variant === 'inverted' && classes.invertedBackground,
        )}
        cx='25'
        cy='25'
        r='20'
        fill='none'
        strokeWidth='5'
      ></circle>
      <circle
        className={cl(classes.spinnerCircle, classes[variant])}
        cx='25'
        cy='25'
        r='20'
        fill='none'
        strokeWidth='5'
        ref={strokeRef}
      ></circle>
    </svg>
  );
};

Spinner.displayName = 'Spinner';

// packages/svelte/src/lib/components/Spinner/Spinner.svelte
<script>
  /**
   * Sets the title of the spinner for accessibility purposes.
   * @type {string}
   */
  export let title = '';

  /**
   * The size of the spinner to render. Options are 'xSmall', 'small', 'medium', 'large', '1xLarge', '2xLarge', '3xLarge'. Defaults to 'medium'.
   * @type {'xSmall' | 'small' | 'medium' | 'large' | 'xLarge'}
   */
  export let size = 'medium';

  /**
   * What variant of the spinner to render. Options are 'default', 'interaction', 'inverted'. Defaults to 'default'.
   * @type {'default' | 'interaction' | 'inverted'}
   */
  export let variant = 'default';
  export let className = '';

  const sizeMap = {
    xSmall: 15,
    small: 23,
    medium: 51,
    large: 67,
    xLarge: 101,
  };

  const strokeWidthMap = {
    xSmall: 5,
    small: 4.5,
    medium: 5,
    large: 4.2,
    xLarge: 4.5,
  };

  const variantMap = {
    default: {
      foreground: 'defaultForeground',
      background: 'defaultBackground',
    },
    interaction: {
      foreground: 'interactionForeground',
      background: 'interactionBackground',
    },
    inverted: {
      foreground: 'invertedForeground',
      background: 'invertedBackground',
    },
  };

  const styles = {
    width: `${sizeMap[size]}px`,
    height: `${sizeMap[size]}px`,
  };
</script>

<svg
  class="spinner {className}"
  viewBox="0 0 50 50"
  width={styles.width}
  height={styles.height}
  {...$$restProps}
>
  <title>{title}</title>
  <circle
    class={variantMap[variant].background}
    cx="25"
    cy="25"
    r="20"
    stroke-width={strokeWidthMap[size]}
    fill="none"
  />
  <circle
    class="spinnerCircle {variantMap[variant].foreground}"
    cx="25"
    cy="25"
    r="20"
    stroke-width={strokeWidthMap[size]}
    fill="none"
  />
</svg>

<style lang="scss">
  .spinner {
    animation: rotate-animation 1s linear infinite;
  }

  .spinnerCircle {
    animation: stroke-animation 1.5s ease-in-out infinite;
  }

  .defaultForeground {
    stroke: var(--colors-grey-500, #a5aab1);
  }

  .interactionForeground {
    stroke: var(--fds-semantic-border-action-first-default, #0062ba);
  }

  .invertedForeground {
    stroke: var(--colors-white, #ffffff);
  }

  .defaultBackground,
  .interactionBackground,
  .invertedBackground {
    stroke: var(--colors-grey-200, #e9eaec);
  }

  @keyframes rotate-animation {
    100% {
      transform: rotate(360deg);
    }
  }

  @keyframes stroke-animation {
    0% {
      stroke-dasharray: 1, 150;
      stroke-dashoffset: 0;
    }

    50% {
      stroke-dasharray: 90, 150;
      stroke-dashoffset: -62;
    }

    100% {
      stroke-dasharray: 90, 150;
      stroke-dashoffset: -124;
    }
  }
</style>
