// packages/web-components/src/components/Details/DetailsContent.ts
import { html, render } from 'lit';

export type DetailsContentArgs = {
  /** Heading text */
  // children: HTMLElement;
};

/**
 * Details content component, contains the content of the details item.
 * @example
 * <ds-details-content>Content</ds-details-content>
 */
export class DetailsContent extends HTMLDivElement {
  constructor() {
    super();
  }

  connectedCallback() {
    render(`<slot></slot>`, this);
  }
};

// packages/react/src/components/Details/DetailsContent.tsx
import type { HTMLAttributes } from 'react';
import { forwardRef } from 'react';

export type DetailsContentProps = HTMLAttributes<HTMLDivElement>;

/**
 * Details content component, contains the content of the details item.
 * @example
 * <DetailsContent>Content</DetailsContent>
 */
export const DetailsContent = forwardRef<HTMLDivElement, DetailsContentProps>(
  function DetailsContent(rest, ref) {
    return <div ref={ref} {...rest} />;
  },
);
