// packages/react/src/components/Details/DetailsSummary.tsx
import type { HTMLAttributes, ReactNode } from 'react';
import { forwardRef } from 'react';

export type DetailsSummaryProps = {
  /** Heading text */
  children: ReactNode;
} & HTMLAttributes<HTMLElement>;

/**
 * Details summary component, contains a the heading to toggle the content.
 * @example
 * <Details.Summary>Heading</Details.Summary>
 */
export const DetailsSummary = forwardRef<HTMLElement, DetailsSummaryProps>(
  function DetailsSummary({ className, ...rest }, ref) {
    /* Set `className` as `class` so react is happy */
    return <u-summary ref={ref} class={className} {...rest} />;
  },
);

// packages/web-components/src/components/Details/DetailsSummary.ts
import { html, render } from 'lit';

export type DetailsSummaryArgs = {
  /** Heading text */
  // children: HTMLElement;
};

/**
 * Details summary component, contains a the heading to toggle the content.
 * @example
 * <ds-details-summary>Heading</ds-details-summary>
 */
export class DetailsSummary extends HTMLElement {
  constructor() {
    super();
  }

  connectedCallback() {
    render(html`<u-summary class=${this.className}><slot></slot></u-summary>`, this);
  }
};
