// packages/react/src/components/form/CharacterCounter.tsx
import React from 'react';

import utilityClasses from '../../utilities/utility.module.css';
import { ErrorMessage } from '../Typography';

export type CharacterLimitProps = Omit<
  CharacterCounterProps,
  'id' | 'value' | 'size'
>;

type CharacterCounterProps = {
  /** The message indicating the remaining character limit. */
  label?: (count: number) => string;
  /** The description of the maximum character limit for screen readers. */
  srLabel?: string;
  /** The maximum allowed character count. */
  maxCount: number;
  /** The current value. */
  value: string;
  /** The ID of the element that describes the maximum character limit for accessibility purposes. */
  id: string;
  /** Text size */
  size?: 'xsmall' | 'small' | 'medium' | 'large';
};

const defaultLabel: CharacterCounterProps['label'] = (count) =>
  count > -1 ? `${count} tegn igjen` : `${Math.abs(count)} tegn for mye`;

const defaultSrLabel = (maxCount: number) =>
  `Tekstfelt med plass til ${maxCount} tegn`;

export const CharacterCounter = ({
  label = defaultLabel,
  srLabel: propsSrLabel,
  maxCount,
  value,
  id,
  size,
}: CharacterCounterProps): JSX.Element => {
  const currentCount = maxCount - value.length;
  const hasExceededLimit = value.length > maxCount;
  const srLabel = propsSrLabel ? propsSrLabel : defaultSrLabel(maxCount);

  return (
    <>
      <span
        className={utilityClasses.visuallyHidden}
        id={id}
      >
        {srLabel}
      </span>
      <ErrorMessage
        as='span'
        size={size}
        aria-live={hasExceededLimit ? 'polite' : 'off'}
        error={hasExceededLimit}
      >
        {label(currentCount)}
      </ErrorMessage>
    </>
  );
};

// packages/svelte/src/lib/components/Form/CharacterCounter.svelte
<script>
  export let label = defaultLabel;
  export let srLabel = '';
  export let maxCount;
  export let value;
  export let id;
  export let size = 'medium';

  let fontSizeClass;
  switch (size) {
    case 'xsmall':
      fontSizeClass = 'font-xsmall';
      break;
    case 'small':
      fontSizeClass = 'font-small';
      break;
    case 'medium':
      fontSizeClass = 'font-medium';
      break;
    case 'large':
      fontSizeClass = 'font-large';
      break;
    default:
      fontSizeClass = 'font-medium';
      break;
  }

  function defaultLabel(count) {
    return count > -1
      ? `${count} tegn igjen`
      : `${Math.abs(count)} tegn for mye`;
  }

  function defaultSrLabel(maxCount) {
    return `Tekstfelt med plass til ${maxCount} tegn`;
  }

  $: currentCount = maxCount - value.length;
  $: hasExceededLimit = value.length > maxCount;
  $: finalSrLabel = srLabel || defaultSrLabel(maxCount);
</script>

<span
  class={`visuallyHidden ${fontSizeClass}`}
  {id}
>
  {finalSrLabel}
</span>

<span
  class={`${hasExceededLimit ? 'error' : ''} ${fontSizeClass}`}
  aria-live={hasExceededLimit ? 'polite' : 'off'}
>
  {label ? label(currentCount) : defaultLabel(currentCount)}
</span>

<style>
  .error {
    color: red;
  }

  .visuallyHidden {
    position: absolute !important;
    height: 1px;
    width: 1px;
    overflow: hidden;
    clip: rect(1px 1px 1px 1px);
    clip: rect(1px, 1px, 1px, 1px);
  }

  .font-xsmall {
    font-size: 0.8125rem;
  }
  .font-small {
    font-size: 0.9375rem;
  }
  .font-medium {
    font-size: 1.125rem;
  }
  .font-large {
    font-size: 1.25rem;
  }
</style>
