// packages/core/src/components/Typography/Heading/Heading.tsx
import React from 'react';
import cn from 'classnames';

import classes from './Heading.module.css';

export interface HeadingProps {
  level?: HeadingLevel;
  size?: HeadingSize;
  color?: string;
  children: React.ReactNode;
  margin?: boolean;
}

export enum HeadingSize {
  XLarge = 'xlarge',
  Large = 'large',
  Medium = 'medium',
  Small = 'small',
  XSmall = 'xsmall',
}

export enum HeadingLevel {
  H1 = 1,
  H2 = 2,
  H3 = 3,
  H4 = 4,
  H5 = 5,
  H6 = 6,
}

const Heading = ({
  level = HeadingLevel.H1,
  size = HeadingSize.XLarge,
  color = 'black',
  children,
  margin = false,
}: HeadingProps) => {
  const Heading = ({ ...props }: React.HTMLAttributes<HTMLHeadingElement>) => {
    return React.createElement('h' + level, props, children);
  };
  const HeadingStyle = {
    color,
  };
  return (
    <Heading
      style={HeadingStyle}
      className={cn(
        [classes['heading']],
        { [classes['heading--margin']]: margin },
        classes['heading--' + size],
      )}
    >
      {children}
    </Heading>
  );
};

export default Heading;

// packages/svelte/src/lib/components/Typography/Heading/Heading.svelte
<script>
	/**
	 * @prop {string} [size='xlarge'] - Specify the size. Options are 'xxsmall', 'xsmall', 'small', 'medium', 'large' and 'xlarge'.
	 */
	export let level = 1;
	export let size = 'xlarge';
	export let spacing = false;
	export let className = '';

	let Component = level && `h${level}`;
	$: classes = ` ${className} heading ${size} ${spacing ? 'spacing' : ''}`;
</script>

{#if Component === 'h1'}
	<h1 class="{classes} {size} {spacing ? 'spacing' : ''}"><slot /></h1>
{:else if Component === 'h2'}
	<h2 class="{classes} {size} {spacing ? 'spacing' : ''}"><slot /></h2>
{:else if Component === 'h3'}
	<h3 class="{classes} {size} {spacing ? 'spacing' : ''}"><slot /></h3>
{:else if Component === 'h4'}
	<h4 class="{classes} {size} {spacing ? 'spacing' : ''}"><slot /></h4>
{:else if Component === 'h5'}
	<h5 class="{classes} {size} {spacing ? 'spacing' : ''}"><slot /></h5>
{:else if Component === 'h6'}
	<h6 class="{classes} {size} {spacing ? 'spacing' : ''}"><slot /></h6>
{/if}

<style>
	.header {
		margin: 0;
	}

	.heading.spacing {
		margin-bottom: var(--fdsc-bottom-spacing);
	}

	.heading.xlarge {
		--fdsc-bottom-spacing: var(--fds-spacing-6);

		font: var(--fds-typography-heading-xlarge);
		font-family: var(--fdsc-typography-font-family);
	}

	.heading.large {
		--fdsc-bottom-spacing: var(--fds-spacing-5);

		font: var(--fds-typography-heading-large);
		font-family: var(--fdsc-typography-font-family);
	}

	.heading.medium {
		--fdsc-bottom-spacing: var(--fds-spacing-4);

		font: var(--fds-typography-heading-medium);
		font-family: var(--fdsc-typography-font-family);
	}

	.heading.small {
		--fdsc-bottom-spacing: var(--fds-spacing-3);

		font: var(--fds-typography-heading-small);
		font-family: var(--fdsc-typography-font-family);
	}

	.heading.xsmall {
		--fdsc-bottom-spacing: var(--fds-spacing-2);

		font: var(--fds-typography-heading-xsmall);
		font-family: var(--fdsc-typography-font-family);
	}

	.heading.xxsmall {
		--fdsc-bottom-spacing: var(--fds-spacing-1);

		font: var(--fds-typography-heading-xxsmall);
		font-family: var(--fdsc-typography-font-family);
	}
</style>
